events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
          ^

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177:11)
    at emitNone (events.js:106:13)
    at process.emit (events.js:208:7)
    at Signal.wrap.onsignal (internal/process.js:208:44)
C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
          ^

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177:11)
    at emitNone (events.js:106:13)
    at process.emit (events.js:208:7)
    at Signal.wrap.onsignal (internal/process.js:208:44)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at process.killkid (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177:11)
    at emitNone (events.js:106:13)
    at process.emit (events.js:208:7)
    at Signal.wrap.onsignal (internal/process.js:208:44)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at process.killkid (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177:11)
    at emitNone (events.js:106:13)
    at process.emit (events.js:208:7)
    at Signal.wrap.onsignal (internal/process.js:208:44)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EROFS
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at exports.fork (child_process.js:103:10)
    at launch (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:153:11)
    at Timeout._onTimeout (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:110:9)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\app.js:16:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\app.js:16:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\app.js:16:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
          ^

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:177:11)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process.exit (internal/process.js:157:15)
    at monitor (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:99:17)
    at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:170:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:23
    at NativeModule.compile (bootstrap_node.js:597:7)
    at NativeModule.require (bootstrap_node.js:542:18)
    at net.js:45:13
    at NativeModule.compile (bootstrap_node.js:597:7)
    at NativeModule.require (bootstrap_node.js:542:18)
    at internal/child_process.js:6:13
    at NativeModule.compile (bootstrap_node.js:597:7)
    at NativeModule.require (bootstrap_node.js:542:18)
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EROFS
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at Object.elevate (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\binaries.js:44:5)
    at write (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\eventlog.js:61:10)
    at logger.value [as warn] (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\eventlog.js:173:9)
    at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:157:9)
    at emitTwo (events.js:126:13)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:425:8)
    at Protocol.emit (events.js:311:20)
    at Protocol._delegateError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:390:10)
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
Error: No default engine was specified and no extension was provided.
    at new View (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\view.js:61:11)
    at Function.render (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\response.js:1008:7)
    at C:\xampp\htdocs\smop-invoice-backend\routes\index.js:6:7
    at Layer.handle [as handle_request] (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\router\layer.js:95:5)
    at C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\xampp\htdocs\smop-invoice-backend\node_modules\express\lib\router\index.js:335:12)
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:425:8)
    at Protocol.emit (events.js:311:20)
    at Protocol._delegateError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:390:10)
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
WSAStartup: (10107) A system call has failed.
internal/child_process.js:407
    throw errnoException(err, 'spawn');
    ^

Error: spawn EROFS
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:548:9)
    at Object.execFile (child_process.js:232:17)
    at exec (child_process.js:153:25)
    at Object.elevate (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\binaries.js:44:5)
    at write (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\eventlog.js:61:10)
    at logger.value [as warn] (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\eventlog.js:173:9)
    at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js:157:9)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  errno: 'EROFS',
  code: 'EROFS',
  syscall: 'spawn'
}
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:425:8)
    at Protocol.emit (events.js:311:20)
    at Protocol._delegateError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:390:10)
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:425:8)
    at Protocol.emit (events.js:311:20)
    at Protocol._delegateError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:390:10)
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:425:8)
    at Protocol.emit (events.js:311:20)
    at Protocol._delegateError (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:390:10)
    at Protocol.end (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (C:\xampp\htdocs\smop-invoice-backend\node_modules\mysql\lib\Connection.js:97:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
